services:
  docs:
    image: easy_charge_local_docs
    container_name: easy_charge_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./easy_charge:/app/easy_charge:z
    ports:
      - '9000:9000'
    command: /start-docs
