# Generated by Django 4.2.14 on 2024-07-25 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_vendorprofile_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Vendor Name')),
                ('is_verify', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Balance')),
                ('owner', models.OneToOneField(limit_choices_to={'is_verify': True}, on_delete=django.db.models.deletion.CASCADE, to='users.vendorprofile', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.PositiveIntegerField(verbose_name='Charge Amount')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customerprofile', verbose_name='Charge Buyer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('approved', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(limit_choices_to={'is_verify': True}, on_delete=django.db.models.deletion.CASCADE, to='reseller.vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
