# Generated by Django 4.2.14 on 2024-07-26 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequest',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount'),
        ),
    ]
