# Generated by Django 4.2.14 on 2024-07-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_alter_creditrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reseller.vendor', verbose_name='Vendor'),
        ),
    ]
